# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ai_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61i_service.proto\x12\nai_service\"T\n\tAiRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x0f\n\x07\x61pi_key\x18\x02 \x01(\t\x12\x17\n\nsession_id\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\r\n\x0b_session_id\"2\n\nAiResponse\x12\x10\n\x08response\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\"*\n\x17ProjectStructureRequest\x12\x0f\n\x07\x61pi_key\x18\x01 \x01(\t\"-\n\x18ProjectStructureResponse\x12\x11\n\tstructure\x18\x01 \x01(\t2\xb2\x01\n\tAiService\x12\x43\n\x12GenerateAiResponse\x12\x15.ai_service.AiRequest\x1a\x16.ai_service.AiResponse\x12`\n\x13GetProjectStructure\x12#.ai_service.ProjectStructureRequest\x1a$.ai_service.ProjectStructureResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AIREQUEST']._serialized_start=32
  _globals['_AIREQUEST']._serialized_end=116
  _globals['_AIRESPONSE']._serialized_start=118
  _globals['_AIRESPONSE']._serialized_end=168
  _globals['_PROJECTSTRUCTUREREQUEST']._serialized_start=170
  _globals['_PROJECTSTRUCTUREREQUEST']._serialized_end=212
  _globals['_PROJECTSTRUCTURERESPONSE']._serialized_start=214
  _globals['_PROJECTSTRUCTURERESPONSE']._serialized_end=259
  _globals['_AISERVICE']._serialized_start=262
  _globals['_AISERVICE']._serialized_end=440
# @@protoc_insertion_point(module_scope)
