# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ai_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63laude_service.proto\x12\nai_service\"T\n\tAIRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x0f\n\x07\x61pi_key\x18\x02 \x01(\t\x12\x17\n\nsession_id\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\r\n\x0b_session_id\"2\n\nAiResponse\x12\x10\n\x08response\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t2P\n\tAiService\x12\x43\n\x12GenerateAiResponse\x12\x15.ai_service.AIRequest\x1a\x16.ai_service.AiResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'claude_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AIREQUEST']._serialized_start=36
  _globals['_AIREQUEST']._serialized_end=120
  _globals['_AIRESPONSE']._serialized_start=122
  _globals['_AIRESPONSE']._serialized_end=172
  _globals['_AISERVICE']._serialized_start=174
  _globals['_AISERVICE']._serialized_end=254
# @@protoc_insertion_point(module_scope)
